### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by Sakshamrzt** [team-12-csc-510/adilytics#26]
Write docstrings for models, services:
1. Aditya:ad, company
2. Riwik: click, init_db, main.py
3. Saksham:user, product , utils
4. Shubhender:location, health, index

**Comment by ritwiktiwari** [comment]
all remaining undocumented models, all utils, init_db, main.py is done
click route and service done

**Comment by SSingh-07** [comment]
location, health & index docstrings updated.

**Comment by SSingh-07** [comment]
Doc Strings are created as per the code requirements.
